server:
  port: 8282
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank-management-db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: true
# App Properties
bank-backend:
  app:
    jwtSecret: bankSecretKey
    jwtExpirationMs: 86400000
